// #[macro_use] extern crate time_test;
// #[macro_use] extern crate common_macros;

#[allow(dead_code)]

// mod array_diff;
// mod bleatrix_trotter;
// mod bouncing_balls;
// mod deadfish;
// mod desc_order;
// mod directions_reduction;
// mod divisibility_by_13;
// mod game;
// mod gap_in_primes;
// mod irr_sum_of_rationals;
// mod last_digit_huge_number;
// mod mini_bit_move;
// mod moves_in_squared_strings;
// mod pattern_zoom;
// mod recover_secret_string;
// mod reducing_by_steps;
// mod rolldice_sum_prob;
// mod roman_numerals;
// mod starts_ends_with;
// mod sum_of_pairs;
// mod summy;
// mod word_order;
// mod a_disguised_sequence;
// mod digital_cypher;
// mod find_the_nth_digit;
// mod dec_to_factorial_and_back;
// mod reverse_or_rotate;
// mod validate_sudoku_with_size_nxn;
// mod diophantine_equation;
// mod scheduling_sjf;
// mod bit_counting;
// mod weight_for_weight;
// mod to_leet_speak;
// mod simple_beads_count;
// mod coloured_triangles;
// mod target_date;
// mod build_a_square;
// mod duplicate_encoder;
// mod help_the_bookseller;
// mod bankers_plan;
// mod find_missing_letter;
// mod growth_of_population;
// mod categorize_new_member;
// mod best_travel;
// mod camel_case_method;
// mod rectangle_into_squares;
// mod play_w_passphrases;
// mod cafeteria;
// mod build_pile_cubes;
// mod catalog;
// mod num_int_partitions;
// mod point_in_polygon;
// mod get_along_int_partitions;
// mod sum_by_factors;
// mod primes_in_numbers;
// mod buying_a_car;
// mod backwards_read_primes;
// mod twice_linear;
// mod highest_scoring_word;
// mod range_execution;
// mod simple_sub_cipher_helper;
// mod ball_upwards;
// mod color_choice;
// mod help_granny;
mod character_frequency;

// This one has trouble because it uses a special class
// mod morse_decoder;
